"""Authoritative, machine-readable registry for PA runtime configuration.

This module deliberately contains data, not surface-specific rendering.  The web
page, HTTP/MCP API, noninteractive CLI, and terminal editor all consume the same
definitions so coverage and validation cannot silently diverge.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Literal

SettingKind = Literal[
    "str",
    "optional_str",
    "path",
    "optional_path",
    "int",
    "optional_int",
    "float",
    "bool",
    "list_str",
    "optional_list_str",
    "dict_json",
    "dict_int",
]
ApplyMode = Literal["live", "reload", "restart"]
Exposure = Literal["editable", "read_only", "hidden"]
Scope = Literal["instance", "realm", "fleet", "user", "secret"]

CONFIGURATION_PRECEDENCE = (
    "runtime_override",
    "cli_override",
    "config_file",
    "environment",
    "default",
)


@dataclass(frozen=True)
class SurfaceAccess:
    read: bool = True
    write: bool = False


@dataclass(frozen=True)
class SettingDefinition:
    key: str
    kind: SettingKind
    default: Any
    description: str
    category: str
    order: int
    impact: str
    apply: ApplyMode = "restart"
    scope: Scope = "instance"
    exposure: Exposure = "editable"
    rationale: str = ""
    aliases: tuple[str, ...] = ()
    environment: tuple[str, ...] = ()
    allowed: tuple[str, ...] = ()
    example: str = ""
    secret: bool = False
    list_ops: bool = False
    platforms: tuple[str, ...] = ("all",)
    providers: tuple[str, ...] = ("all",)
    sources: tuple[str, ...] = (
        "default",
        "config_file",
        "environment",
        "cli_override",
        "runtime_override",
    )
    deprecated: bool = False
    replacement: str | None = None
    migration: str | None = None
    normalizer: str | None = None
    validator: str | None = None
    surfaces: dict[str, SurfaceAccess] = field(default_factory=dict)

    @property
    def editable(self) -> bool:
        return self.exposure == "editable"

    # Compatibility names used by the existing terminal editor.
    @property
    def name(self) -> str:
        return self.key

    @property
    def sensitive(self) -> bool:
        return self.secret

    @property
    def dangerous(self) -> bool:
        return self.secret or self.apply == "restart" or "expos" in self.impact.lower()

    def metadata(self) -> dict[str, Any]:
        value = asdict(self)
        value["editable"] = self.editable
        value["restart_required"] = self.apply == "restart"
        value["reload_required"] = self.apply == "reload"
        value["precedence"] = list(CONFIGURATION_PRECEDENCE)
        return value


def _surface_access(exposure: Exposure) -> dict[str, SurfaceAccess]:
    writable = exposure == "editable"
    readable = exposure != "hidden"
    return {
        "web": SurfaceAccess(read=readable, write=writable),
        "cli": SurfaceAccess(read=readable, write=writable),
        "api": SurfaceAccess(read=readable, write=writable),
        "mcp": SurfaceAccess(read=readable, write=writable),
        "environment": SurfaceAccess(read=True, write=False),
        "config_file": SurfaceAccess(read=True, write=writable),
    }


def _s(
    key: str,
    kind: SettingKind,
    default: Any,
    description: str,
    category: str,
    order: int,
    impact: str,
    *,
    apply: ApplyMode = "restart",
    scope: Scope = "instance",
    exposure: Exposure = "editable",
    rationale: str = "",
    aliases: tuple[str, ...] = (),
    environment: tuple[str, ...] = (),
    allowed: tuple[str, ...] = (),
    example: str = "",
    secret: bool = False,
    list_ops: bool = False,
    platforms: tuple[str, ...] = ("all",),
    providers: tuple[str, ...] = ("all",),
    sources: tuple[str, ...] = (
        "default",
        "config_file",
        "environment",
        "cli_override",
        "runtime_override",
    ),
    deprecated: bool = False,
    replacement: str | None = None,
    migration: str | None = None,
    normalizer: str | None = None,
    validator: str | None = None,
) -> SettingDefinition:
    return SettingDefinition(
        key=key,
        kind=kind,
        default=default,
        description=description,
        category=category,
        order=order,
        impact=impact,
        apply=apply,
        scope=scope,
        exposure=exposure,
        rationale=rationale,
        aliases=aliases,
        environment=environment or (f"PA_{key.upper()}",),
        allowed=allowed,
        example=example,
        secret=secret,
        list_ops=list_ops,
        platforms=platforms,
        providers=providers,
        sources=sources,
        deprecated=deprecated,
        replacement=replacement,
        migration=migration,
        normalizer=normalizer,
        validator=validator,
        surfaces=_surface_access(exposure),
    )


_DEFINITIONS = (
    _s(
        "instance_id",
        "str",
        "<generated>",
        "Stable instance UUID.",
        "Identity",
        10,
        "Changing identity would orphan durable fleet and sync records.",
        exposure="read_only",
        rationale="Created once by `pa init`; identity changes use migration tooling.",
        sources=("config_file",),
        validator="uuid",
    ),
    _s(
        "instance_name",
        "str",
        "local",
        "Human-readable instance name.",
        "Identity",
        20,
        "Changes labels advertised to the fleet and shown in the UI.",
        apply="reload",
        validator="non_empty",
    ),
    _s(
        "data_dir",
        "path",
        "~/.pa",
        "PA state and database directory.",
        "Storage",
        10,
        "Selects all durable local state and the single-writer boundary.",
        exposure="read_only",
        rationale="Bootstrap-only; select it with PA_DATA_DIR before PA starts.",
        sources=("default", "environment", "cli_override"),
        validator="path",
    ),
    _s(
        "workspace_root",
        "optional_path",
        None,
        "Root for leased repository worktrees.",
        "Storage",
        20,
        "Moves mutable source workspaces; it must remain outside data_dir.",
        validator="workspace_outside_data_dir",
        example="/srv/pa-workspaces",
    ),
    _s(
        "host",
        "optional_str",
        "127.0.0.1",
        "Legacy web bind address.",
        "Network",
        10,
        "A public bind can expose PA to the network.",
        apply="restart",
        example="127.0.0.1",
        validator="bind_host",
    ),
    _s(
        "web_listeners",
        "list_str",
        [],
        "Explicit HOST or HOST:PORT web bind listeners.",
        "Network",
        20,
        "Controls every HTTP listener; public listeners increase exposure.",
        apply="restart",
        list_ops=True,
        example="127.0.0.1:8080",
        validator="web_listeners",
    ),
    _s(
        "port",
        "int",
        8080,
        "Default HTTP port.",
        "Network",
        30,
        "Changes local and advertised HTTP endpoints.",
        apply="restart",
        example="8080",
        validator="tcp_port",
    ),
    _s(
        "instance_url",
        "optional_str",
        "",
        "Advertised reachable instance URL.",
        "Network",
        40,
        "Fleet peers use this URL to reach the instance.",
        apply="reload",
        example="https://pa.example:8080",
        validator="non_loopback_http_url",
    ),
    _s(
        "peers",
        "list_str",
        [],
        "Peer instance base URLs.",
        "Network",
        50,
        "Adds outbound sync/discovery destinations.",
        apply="reload",
        list_ops=True,
        example="https://peer.example:8080",
        validator="http_url_list",
    ),
    _s(
        "fleet_id",
        "str",
        "<generated>",
        "Canonical fleet UUID.",
        "Fleet",
        10,
        "Partitions membership and dispatch authority.",
        scope="fleet",
        exposure="read_only",
        rationale="Managed atomically by fleet create/join workflows.",
        sources=("config_file",),
        validator="uuid",
    ),
    _s(
        "fleet_owner",
        "str",
        "local",
        "Canonical fleet-owner instance ID.",
        "Fleet",
        20,
        "Defines fleet policy authority.",
        scope="fleet",
        exposure="read_only",
        rationale="Managed by authenticated fleet join and ownership workflows.",
        sources=("config_file",),
        validator="non_empty",
    ),
    _s(
        "fleet_owner_url",
        "optional_str",
        "",
        "Fleet-owner base URL.",
        "Fleet",
        30,
        "Routes owner-authoritative fleet operations.",
        apply="reload",
        scope="fleet",
        example="https://owner.example:8080",
        validator="http_url",
    ),
    _s(
        "pr_supervisor_authority_url",
        "optional_str",
        "",
        "Fenced PR-supervisor authority URL.",
        "Fleet",
        40,
        "Routes merge supervision and merge-on-green decisions.",
        apply="reload",
        scope="fleet",
        example="https://owner.example:8080",
        validator="http_url",
    ),
    _s(
        "subscribed_realms",
        "list_str",
        ["default"],
        "Realm IDs synchronized by this instance.",
        "Fleet",
        50,
        "Changes replicated data boundaries.",
        apply="reload",
        scope="realm",
        list_ops=True,
        validator="non_empty_list",
    ),
    _s(
        "zone",
        "str",
        "default",
        "Placement/network zone label.",
        "Fleet",
        60,
        "Influences placement and locality decisions.",
        apply="reload",
        scope="fleet",
        validator="non_empty",
    ),
    _s(
        "capabilities",
        "list_str",
        [],
        "Advertised fleet capability tags.",
        "Fleet",
        70,
        "Changes placement eligibility.",
        apply="reload",
        scope="fleet",
        list_ops=True,
    ),
    _s(
        "dispatch_capacity",
        "optional_int",
        None,
        "Global concurrent execution slots.",
        "Execution",
        10,
        "Caps new fleet placement admissions.",
        apply="live",
        scope="fleet",
        example="4",
        validator="dispatch_capacity",
    ),
    _s(
        "dispatch_provider_capacities",
        "dict_int",
        {},
        "Per-provider execution slot ceilings.",
        "Execution",
        20,
        "Caps new admissions for individual providers.",
        apply="live",
        scope="fleet",
        example='{"codex": 2}',
        validator="provider_capacities",
        normalizer="lowercase_keys",
    ),
    _s(
        "dispatch_queue_capacity",
        "int",
        100,
        "Maximum durably waiting dispatches.",
        "Execution",
        30,
        "Rejects new queued work only after this bounded waiting queue is full.",
        apply="live",
        scope="fleet",
        example="100",
        validator="dispatch_queue_capacity",
    ),
    _s(
        "dispatch_provider_queue_capacities",
        "dict_int",
        {},
        "Optional per-provider waiting queue ceilings.",
        "Execution",
        40,
        "Applies together with the instance queue limit; the lower value wins.",
        apply="live",
        scope="fleet",
        example='{"codex": 50}',
        validator="provider_queue_capacities",
        normalizer="lowercase_keys",
    ),
    _s(
        "relay_enabled",
        "bool",
        False,
        "Allow this instance to relay fleet traffic.",
        "Fleet",
        80,
        "May forward traffic between peers.",
        apply="reload",
        scope="fleet",
    ),
    _s(
        "cloud_endpoint",
        "optional_str",
        "",
        "Optional PA cloud coordination service URL.",
        "Cloud",
        10,
        "Routes lease fencing and shared-state publications to an external service.",
        example="https://coordination.example",
        validator="http_url",
    ),
    _s(
        "cloud_token",
        "optional_str",
        "",
        "Bearer credential for the cloud coordination service.",
        "Cloud",
        20,
        "Replacing it changes cloud authentication for this instance.",
        scope="secret",
        secret=True,
        validator="secret",
    ),
    _s(
        "cloud_timeout_seconds",
        "float",
        5.0,
        "Cloud lease request timeout in seconds.",
        "Cloud",
        30,
        "Bounds how long lease admission waits for the cloud service.",
    ),
    _s(
        "cloud_lease_fail_open",
        "bool",
        True,
        "Allow local lease admission during a cloud outage.",
        "Cloud",
        40,
        "Disabling this favors global fencing over availability.",
    ),
    _s(
        "cloud_publish_queue_capacity",
        "int",
        1000,
        "Maximum buffered cloud state publications.",
        "Cloud",
        50,
        "Bounds memory used while cloud publication is slower than local mutations.",
    ),
    _s(
        "cloud_allow_insecure_http",
        "bool",
        False,
        "Permit an HTTP cloud endpoint for isolated development.",
        "Cloud",
        60,
        "Enabling this can expose credentials and coordination traffic.",
    ),
    _s(
        "sync_token",
        "optional_str",
        "",
        "Shared credential for peer synchronization.",
        "Secrets",
        10,
        "Replacing it invalidates peer authentication until all peers match.",
        apply="reload",
        scope="secret",
        secret=True,
        validator="secret",
        environment=("PA_SYNC_TOKEN", "PA_SYNC_TOKEN_FILE"),
    ),
    _s(
        "sync_token_previous",
        "list_str",
        [],
        "Managed overlap credentials for fleet rotation.",
        "Secrets",
        11,
        "PA manages this list through the audited rotation workflow only.",
        apply="live",
        scope="secret",
        exposure="hidden",
        rationale="Use pa fleet credential rotation commands; never edit overlap credentials directly.",
        secret=True,
        list_ops=False,
        sources=("config_file", "runtime_override"),
    ),
    _s(
        "auth_required",
        "bool",
        False,
        "Require user authentication for UI/API access.",
        "Authentication",
        10,
        "Enables the user authentication boundary.",
        apply="restart",
    ),
    _s(
        "secure_cookies",
        "bool",
        False,
        "Require HTTPS-only browser cookies.",
        "Authentication",
        20,
        "Prevents cookies over plaintext HTTP; requires HTTPS access.",
        apply="restart",
    ),
    _s(
        "session_secret",
        "optional_str",
        "<generated>",
        "Cookie and session signing secret.",
        "Secrets",
        20,
        "Replacing it invalidates browser sessions and CSRF tokens.",
        apply="restart",
        scope="secret",
        secret=True,
        validator="secret",
    ),
    _s(
        "intake_max_event_bytes",
        "int",
        2 * 1024 * 1024,
        "Maximum signed channel event size in bytes.",
        "Channel intake",
        10,
        "Bounds memory and storage used by any one inbound provider event.",
        apply="reload",
    ),
    _s(
        "intake_max_artifact_bytes",
        "int",
        25 * 1024 * 1024,
        "Maximum downloaded artifact size in bytes.",
        "Channel intake",
        20,
        "Bounds each image, audio, video, or file before inspection and storage.",
        apply="reload",
    ),
    _s(
        "intake_raw_retention_hours",
        "float",
        168.0,
        "Retention window for raw channel payloads and source artifacts.",
        "Channel intake",
        30,
        "Expired source content is redacted and unreferenced local blobs are removed.",
        apply="reload",
    ),
    _s(
        "intake_canonical_retention_hours",
        "float",
        2160.0,
        "Retention window for canonical intake envelopes.",
        "Channel intake",
        40,
        "Expired canonical content and identity details are redacted in durable history.",
        apply="reload",
    ),
    _s(
        "intake_identity_rate_limit",
        "int",
        30,
        "Per-channel-identity intake events allowed per minute.",
        "Channel intake",
        50,
        "Limits abuse from one linked or allowlisted provider identity.",
        apply="reload",
    ),
    _s(
        "intake_conversation_rate_limit",
        "int",
        120,
        "Per-conversation intake events allowed per minute.",
        "Channel intake",
        60,
        "Limits bursts from a direct message, group, channel, thread, or topic.",
        apply="reload",
    ),
    _s(
        "intake_channel_routes",
        "dict_json",
        {},
        "Provider conversation routes to realm, project, and goal IDs.",
        "Channel intake",
        70,
        "Controls the durable scope assigned before external content is admitted.",
        apply="reload",
        example='{"telegram:-1001": {"realm_id": "default", "project_id": "p"}}',
    ),
    _s(
        "telegram_bot_token",
        "optional_str",
        "",
        "Telegram Bot API token.",
        "Channel intake",
        80,
        "Authenticates webhook registration, file retrieval, and replies.",
        apply="restart",
        scope="secret",
        secret=True,
        validator="secret",
    ),
    _s(
        "telegram_webhook_secret",
        "optional_str",
        "",
        "Telegram webhook secret token.",
        "Channel intake",
        90,
        "Authenticates every inbound Telegram webhook before parsing.",
        apply="restart",
        scope="secret",
        secret=True,
        validator="secret",
    ),
    _s(
        "telegram_webhook_url",
        "optional_str",
        "",
        "Public HTTPS Telegram webhook URL.",
        "Channel intake",
        100,
        "Registers the signed callback endpoint when PA starts.",
        apply="restart",
        example="https://pa.example/api/intake/webhooks/telegram",
        validator="http_url",
    ),
    _s(
        "telegram_allowed_user_ids",
        "list_str",
        [],
        "Telegram user IDs admitted without explicit identity linking.",
        "Channel intake",
        110,
        "Bypasses account linking for only the listed provider identities.",
        apply="reload",
        list_ops=True,
    ),
    _s(
        "telegram_allowed_conversation_ids",
        "list_str",
        [],
        "Telegram chat IDs admitted without explicit identity linking.",
        "Channel intake",
        120,
        "Admits all non-bot senders in only the listed chats or topics.",
        apply="reload",
        list_ops=True,
    ),
    _s(
        "discord_bot_token",
        "optional_str",
        "",
        "Discord bot token.",
        "Channel intake",
        130,
        "Authenticates the managed Gateway connection, artifact retrieval, and replies.",
        apply="restart",
        scope="secret",
        secret=True,
        validator="secret",
    ),
    _s(
        "discord_application_public_key",
        "optional_str",
        "",
        "Discord application Ed25519 public key in hexadecimal.",
        "Channel intake",
        140,
        "Verifies signed Discord Event Webhooks; this value is not a secret.",
        apply="restart",
    ),
    _s(
        "discord_allowed_user_ids",
        "list_str",
        [],
        "Discord user IDs admitted without explicit identity linking.",
        "Channel intake",
        150,
        "Bypasses account linking for only the listed provider identities.",
        apply="reload",
        list_ops=True,
    ),
    _s(
        "discord_allowed_conversation_ids",
        "list_str",
        [],
        "Discord channel IDs admitted without explicit identity linking.",
        "Channel intake",
        160,
        "Admits all non-bot senders in only the listed channels or threads.",
        apply="reload",
        list_ops=True,
    ),
    _s(
        "oidc_issuer",
        "optional_str",
        "",
        "OIDC issuer URL.",
        "Authentication",
        30,
        "Selects the external identity authority.",
        apply="restart",
        validator="http_url",
    ),
    _s(
        "oidc_client_id",
        "optional_str",
        "",
        "OIDC client identifier.",
        "Authentication",
        40,
        "Identifies PA to the OIDC provider.",
        apply="restart",
    ),
    _s(
        "oidc_client_secret",
        "optional_str",
        "",
        "OIDC client secret.",
        "Secrets",
        30,
        "Authenticates PA to the OIDC provider.",
        apply="restart",
        scope="secret",
        secret=True,
        validator="secret",
    ),
    _s(
        "agent_provider",
        "str",
        "cursor",
        "Default ACP agent provider.",
        "Agent",
        10,
        "Changes the provider used for new sessions.",
        apply="reload",
        allowed=("cursor", "codex", "openinterpreter"),
        validator="agent_provider",
        normalizer="lowercase",
    ),
    _s(
        "agent_command",
        "optional_str",
        None,
        "ACP provider command override.",
        "Agent",
        20,
        "Runs the configured local executable for new provider processes.",
        apply="reload",
        example="/usr/local/bin/agent",
    ),
    _s(
        "agent_args",
        "optional_list_str",
        None,
        "ACP provider argument override.",
        "Agent",
        30,
        "Changes arguments passed to new provider processes.",
        apply="reload",
        list_ops=True,
    ),
    _s(
        "agent_enabled",
        "bool",
        True,
        "Enable ACP agent connectivity.",
        "Agent",
        40,
        "Disabling prevents new local agent sessions.",
        apply="restart",
    ),
    _s(
        "agent_github_token_enabled",
        "bool",
        False,
        "Inject the instance-local GitHub credential into ACP providers as GH_TOKEN.",
        "Agent",
        45,
        "Enabling gives every agent process on this instance the credential's repository access.",
        apply="restart",
    ),
    _s(
        "agent_recovery_concurrency",
        "int",
        2,
        "Concurrent provider recoveries at startup.",
        "Agent",
        50,
        "Higher values recover faster but increase provider load.",
        apply="restart",
        validator="range:1:16",
    ),
    _s(
        "agent_session_idle_retention_hours",
        "float",
        24.0,
        "Idle session retention in hours.",
        "Retention",
        10,
        "Controls how long follow-up-capable idle sessions remain.",
        apply="live",
        validator="range:0.01:8760",
    ),
    _s(
        "agent_session_sweep_seconds",
        "float",
        30.0,
        "Idle-session sweep interval.",
        "Retention",
        20,
        "Short intervals find expired sessions sooner at higher overhead.",
        apply="live",
        validator="range:1:3600",
    ),
    _s(
        "maintenance_interval_seconds",
        "int",
        6 * 60 * 60,
        "How often local cruft cleanup runs.",
        "Retention",
        30,
        "Prunes closed-session transcripts, old mutation receipts, and compactable dispatch evidence.",
        apply="live",
        validator="range:60:604800",
    ),
    _s(
        "transcript_retention_days",
        "int",
        14,
        "Days to keep closed-session transcript events.",
        "Retention",
        40,
        "Deletes transcript payloads for closed sessions older than this; session rows remain.",
        apply="live",
        validator="range:1:3650",
    ),
    _s(
        "mutation_operation_retention_days",
        "int",
        14,
        "Days to keep succeeded or failed mutation receipts.",
        "Retention",
        50,
        "Pending mutation operations are never pruned.",
        apply="live",
        validator="range:1:3650",
    ),
    _s(
        "memory_auto_capture_enabled",
        "bool",
        False,
        "Queue policy-approved memory candidates.",
        "Agent",
        60,
        "May persist reviewed final facts from agent turns.",
        apply="live",
    ),
    _s(
        "card_summary_provider",
        "str",
        "openai",
        "Card-summary provider: openai, anthropic (Claude), or minimax.",
        "Card summaries",
        10,
        "Selects the provider contract, default model, endpoint, and which write-only API key is used. Restart required.",
        allowed=("openai", "anthropic", "minimax"),
    ),
    _s(
        "card_summary_model",
        "str",
        "gpt-5-mini",
        "Model used for semantic card summaries. Provider defaults: gpt-5-mini, claude-haiku-4-5, MiniMax-M2.5.",
        "Card summaries",
        20,
        "Overrides the selected provider's default model. Restart required.",
        validator="non_empty",
        example="claude-sonnet-4-6",
    ),
    _s(
        "card_summary_base_url",
        "str",
        "https://api.openai.com/v1",
        "Override the selected provider's default API base URL.",
        "Card summaries",
        30,
        "OpenAI and MiniMax use OpenAI-compatible /chat/completions. Anthropic uses the native Messages API. MiniMax China host: https://api.minimaxi.com/v1. Restart required.",
        validator="http_url",
        example="https://api.minimaxi.com/v1",
    ),
    _s(
        "card_summary_auth_source",
        "str",
        "dedicated",
        "Credential source for OpenAI card-summary requests.",
        "Card summaries",
        40,
        "Codex dedicated-key fallback applies to openai only. Anthropic and MiniMax always use their write-only Settings keys. Restart required.",
        allowed=("dedicated", "codex"),
    ),
    _s(
        "card_summary_api_key",
        "str",
        "",
        "OpenAI card-summary API key. Write-only; the stored value is never shown.",
        "Card summaries",
        41,
        "Authenticates OpenAI Chat Completions card-summary requests. Restart required.",
        scope="secret",
        secret=True,
        validator="secret",
    ),
    _s(
        "card_summary_anthropic_api_key",
        "str",
        "",
        "Anthropic (Claude) card-summary API key. Write-only; the stored value is never shown.",
        "Card summaries",
        42,
        "Authenticates native Anthropic Messages card-summary requests. Restart required.",
        scope="secret",
        secret=True,
        validator="secret",
    ),
    _s(
        "card_summary_minimax_api_key",
        "str",
        "",
        "MiniMax card-summary API key. Write-only; the stored value is never shown.",
        "Card summaries",
        43,
        "Authenticates MiniMax OpenAI-compatible card-summary requests. Restart required.",
        scope="secret",
        secret=True,
        validator="secret",
    ),
    _s(
        "card_summary_timeout_seconds",
        "float",
        20.0,
        "Timeout for one card-summary provider request.",
        "Card summaries",
        50,
        "Bounds provider latency before a classified retryable failure.",
        validator="range_exclusive_min:0:120",
    ),
    _s(
        "card_summary_max_concurrency",
        "int",
        2,
        "Concurrent card-summary provider requests.",
        "Card summaries",
        60,
        "Bounds provider load and summary-generation cost.",
        validator="range:1:16",
    ),
    _s(
        "card_summary_max_retries",
        "int",
        2,
        "Transient retries after the first summary attempt.",
        "Card summaries",
        70,
        "Bounds durable retry attempts and provider cost.",
        validator="range:0:4",
    ),
    _s(
        "card_summary_retry_base_seconds",
        "float",
        15.0,
        "Initial card-summary retry backoff.",
        "Card summaries",
        80,
        "Controls recovery latency after transient provider failures.",
        validator="range:1:3600",
    ),
    _s(
        "card_summary_retry_max_seconds",
        "float",
        300.0,
        "Maximum card-summary retry backoff.",
        "Card summaries",
        90,
        "Caps delay growth between transient retries.",
        validator="range:1:86400",
    ),
    _s(
        "card_summary_retry_jitter_ratio",
        "float",
        0.2,
        "Maximum proportional jitter added to summary retry backoff.",
        "Card summaries",
        100,
        "Spreads provider retries across independently running installations.",
        validator="range:0:1",
    ),
    _s(
        "card_summary_worker_interval_seconds",
        "float",
        10.0,
        "Interval between bounded card-summary worker scans.",
        "Card summaries",
        110,
        "Controls retry and migration responsiveness versus database overhead.",
        validator="range:1:300",
    ),
    _s(
        "card_summary_migration_batch",
        "int",
        20,
        "Maximum card-summary candidates examined and scheduled per worker interval.",
        "Card summaries",
        120,
        "Bounds migration database work and provider scheduling per interval.",
        validator="range:0:500",
    ),
    _s(
        "post_turn_evaluator_max_attempts",
        "int",
        2,
        "Maximum post-turn evaluator attempts.",
        "Post-turn",
        10,
        "Bounds evaluator retries and provider cost.",
        apply="live",
        validator="range:1:5",
    ),
    _s(
        "post_turn_max_automatic_followups",
        "int",
        2,
        "Maximum automatic follow-ups per turn.",
        "Post-turn",
        20,
        "Bounds autonomous continuation.",
        apply="live",
        validator="range:0:10",
    ),
    _s(
        "post_turn_evaluation_timeout_seconds",
        "float",
        60.0,
        "Post-turn evaluator timeout.",
        "Post-turn",
        30,
        "Bounds time spent evaluating a completed turn.",
        apply="live",
        validator="range_exclusive_min:0:600",
    ),
    _s(
        "post_turn_retry_seconds",
        "float",
        15.0,
        "Post-turn retry delay.",
        "Post-turn",
        40,
        "Controls retry backoff after recoverable evaluation failures.",
        apply="live",
        validator="range_exclusive_min:0:3600",
    ),
    _s(
        "post_turn_escalation_threshold",
        "int",
        2,
        "Failures before operator escalation.",
        "Post-turn",
        50,
        "Controls how quickly repeated automation failures surface.",
        apply="live",
        validator="range:1:10",
    ),
    _s(
        "backup_enabled",
        "bool",
        True,
        "Enable the independent metadata backup schedule.",
        "Backups",
        10,
        "Disabling stops scheduled attempts but preserves retained recovery points.",
        apply="live",
    ),
    _s(
        "backup_interval_seconds",
        "int",
        6 * 60 * 60,
        "Seconds between scheduled metadata backups.",
        "Backups",
        20,
        "Shorter intervals improve recovery point objectives at higher storage and I/O cost.",
        apply="live",
        validator="range:60:2678400",
    ),
    _s(
        "backup_retention_count",
        "int",
        8,
        "Maximum retained verified backup sets.",
        "Backups",
        30,
        "Lower values reduce storage use but leave fewer recovery points.",
        apply="live",
        validator="range:1:10000",
    ),
    _s(
        "backup_retention_max_age_seconds",
        "optional_int",
        None,
        "Optional maximum age for superseded verified backups.",
        "Backups",
        40,
        "Old recovery points are pruned deterministically without deleting the last good copy.",
        apply="live",
        validator="range:60:315360000",
    ),
    _s(
        "backup_retention_max_total_bytes",
        "optional_int",
        None,
        "Optional maximum total size of verified backup archives.",
        "Backups",
        50,
        "Storage pressure prunes oldest superseded recovery points first.",
        apply="live",
        validator="range:1024:9223372036854775807",
    ),
    _s(
        "backup_destination_dir",
        "optional_path",
        None,
        "Private local directory for metadata backup archives.",
        "Backups",
        60,
        "The destination must be outside PA_DATA_DIR and owned by the PA service account.",
        apply="live",
        example="/srv/pa-backups",
        validator="backup_destination",
    ),
    _s(
        "backup_run_on_startup",
        "bool",
        False,
        "Run a backup at startup when the last success is old enough.",
        "Backups",
        70,
        "Enabling may add storage I/O shortly after service startup.",
        apply="live",
    ),
    _s(
        "backup_startup_min_age_seconds",
        "int",
        60 * 60,
        "Minimum last-success age before a startup backup is due.",
        "Backups",
        80,
        "Prevents frequent restarts from creating duplicate recovery points.",
        apply="live",
        validator="range:0:2678400",
    ),
    _s(
        "backup_verification_level",
        "str",
        "full",
        "SQLite integrity verification level for backup archives.",
        "Backups",
        90,
        "Full verification is more thorough; quick verification reduces I/O.",
        apply="live",
        allowed=("quick", "full"),
    ),
    _s(
        "backup_compression",
        "bool",
        True,
        "Compress metadata backup archives.",
        "Backups",
        100,
        "Compression reduces storage use while consuming CPU during backup.",
        apply="live",
    ),
    _s(
        "backup_io_limit_mib_per_second",
        "float",
        None,
        "Optional backup copy throughput limit in MiB per second.",
        "Backups",
        110,
        "A limit reduces storage contention but lengthens backup duration.",
        apply="live",
        validator="range_exclusive_min:0:10000",
    ),
    _s(
        "backup_concurrency",
        "int",
        1,
        "Maximum concurrent backup jobs for this instance.",
        "Backups",
        120,
        "PA currently enforces single-flight backup semantics.",
        apply="live",
        validator="range:1:1",
    ),
    _s(
        "backup_alert_after_failures",
        "int",
        3,
        "Consecutive backup failures before health becomes alerting.",
        "Backups",
        130,
        "Lower thresholds surface destination or integrity failures sooner.",
        apply="live",
        validator="range:1:1000",
    ),
    _s(
        "backup_jitter_seconds",
        "int",
        300,
        "Maximum deterministic jitter added to the backup interval.",
        "Backups",
        140,
        "Jitter spreads storage I/O across independently scheduled fleet instances.",
        apply="live",
        validator="range:0:3600",
    ),
    _s(
        "debug",
        "bool",
        False,
        "Enable debug logging and hook history.",
        "Diagnostics",
        10,
        "May retain more diagnostic metadata and increase log volume.",
        apply="restart",
    ),
    _s(
        "dev_tools",
        "bool",
        False,
        "Expose in-browser developer tools.",
        "Diagnostics",
        20,
        "Shows internal diagnostic panels to authenticated users.",
        apply="restart",
    ),
    _s(
        "log_level",
        "str",
        "INFO",
        "Application log severity threshold.",
        "Diagnostics",
        30,
        "Lower thresholds can record more operational metadata.",
        apply="restart",
        allowed=("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"),
        normalizer="uppercase",
    ),
    _s(
        "log_rotation_max_bytes",
        "int",
        25 * 1024 * 1024,
        "Maximum active service-log bytes before rotation.",
        "Diagnostics",
        40,
        "Smaller values create archives more frequently.",
        apply="restart",
        validator="range:1024:17179869184",
        example="26214400",
    ),
    _s(
        "log_rotation_interval_seconds",
        "float",
        24 * 60 * 60,
        "Maximum active service-log age before rotation.",
        "Diagnostics",
        50,
        "Shorter intervals create archives more frequently.",
        apply="restart",
        validator="range:1:2678400",
    ),
    _s(
        "log_retention_count",
        "int",
        7,
        "Maximum retained service-log archive count.",
        "Diagnostics",
        60,
        "Older archives are removed asynchronously after rotation.",
        apply="restart",
        validator="range:1:10000",
    ),
    _s(
        "log_retention_max_age_seconds",
        "float",
        14 * 24 * 60 * 60,
        "Maximum retained service-log archive age.",
        "Diagnostics",
        70,
        "Archives older than this limit are removed asynchronously.",
        apply="restart",
        validator="range:1:315360000",
    ),
    _s(
        "log_retention_max_total_bytes",
        "int",
        256 * 1024 * 1024,
        "Maximum total bytes retained across active service logs and archives.",
        "Diagnostics",
        80,
        "Active logs are never deleted; they reduce the remaining archive allowance.",
        apply="restart",
        validator="range:1024:68719476736",
        example="268435456",
    ),
    _s(
        "log_disk_pressure_free_bytes",
        "int",
        512 * 1024 * 1024,
        "Minimum free bytes reserved from service logging.",
        "Diagnostics",
        90,
        "Under pressure PA drains and drops service output instead of blocking requests.",
        apply="restart",
        validator="range:0:68719476736",
        example="536870912",
    ),
    _s(
        "blocking_workers",
        "int",
        8,
        "Blocking compatibility worker count.",
        "Performance",
        10,
        "Controls concurrency for blocking compatibility work.",
        apply="restart",
        validator="range:1:64",
    ),
    _s(
        "blocking_queue_limit",
        "int",
        64,
        "Blocking compatibility queue limit.",
        "Performance",
        20,
        "Controls backpressure before blocking work is rejected.",
        apply="restart",
        validator="range:0:4096",
    ),
    _s(
        "blocking_default_timeout",
        "float",
        30.0,
        "Default blocking-operation timeout.",
        "Performance",
        30,
        "Bounds slow compatibility operations.",
        apply="restart",
        validator="range_exclusive_min:0:3600",
    ),
    _s(
        "blocking_slow_call_seconds",
        "float",
        0.5,
        "Slow blocking-call telemetry threshold.",
        "Telemetry",
        10,
        "Changes diagnostic classification only.",
        apply="live",
        validator="range_exclusive_min:0:60",
    ),
    _s(
        "event_loop_probe_interval",
        "float",
        0.1,
        "Event-loop responsiveness probe interval.",
        "Telemetry",
        20,
        "Short intervals improve resolution at modest overhead.",
        apply="restart",
        validator="range_exclusive_min:0:10",
    ),
    _s(
        "telemetry_enabled",
        "bool",
        True,
        "Enable instance resource telemetry.",
        "Telemetry",
        30,
        "Starts bounded host sampling and persistence after restart.",
        apply="restart",
    ),
    _s(
        "telemetry_live_interval_seconds",
        "float",
        5.0,
        "Live telemetry sampling interval.",
        "Telemetry",
        40,
        "Shorter intervals improve freshness at modest collection overhead.",
        apply="live",
        validator="range:1:300",
    ),
    _s(
        "telemetry_persistence_interval_seconds",
        "float",
        30.0,
        "Telemetry persistence interval.",
        "Telemetry",
        50,
        "Controls raw history density and must not be shorter than live sampling.",
        apply="live",
        validator="range:5:3600",
    ),
    _s(
        "telemetry_raw_retention_hours",
        "float",
        168.0,
        "Raw telemetry retention age.",
        "Telemetry",
        60,
        "Older raw samples are deterministically rolled up before deletion.",
        apply="live",
        validator="range:1:8760",
    ),
    _s(
        "telemetry_rollup_retention_hours",
        "float",
        2160.0,
        "Telemetry rollup retention age.",
        "Telemetry",
        70,
        "Bounds long-range history and must not be shorter than raw retention.",
        apply="live",
        validator="range:1:43800",
    ),
    _s(
        "telemetry_max_database_bytes",
        "int",
        512 * 1024 * 1024,
        "Maximum telemetry database size.",
        "Telemetry",
        80,
        "Triggers oldest-first raw rollup and rollup pruning under pressure.",
        apply="live",
        validator="range:16777216:68719476736",
        example="536870912",
    ),
    _s(
        "telemetry_database_path",
        "optional_path",
        None,
        "Independent telemetry SQLite database path.",
        "Telemetry",
        90,
        "Must remain outside PA metadata and sync authority.",
        apply="restart",
        validator="telemetry_database_path",
        example="/var/lib/pa/telemetry.db",
    ),
    _s(
        "telemetry_per_session_enabled",
        "bool",
        True,
        "Collect verified PA-owned agent process trees.",
        "Telemetry",
        100,
        "Adds session attribution where PID ownership remains technically sound.",
        apply="live",
    ),
    _s(
        "telemetry_ui_refresh_seconds",
        "float",
        5.0,
        "Live telemetry UI refresh interval.",
        "Telemetry",
        110,
        "Controls header and agent-chat refresh frequency.",
        apply="live",
        validator="range:2:300",
    ),
    _s(
        "telemetry_default_report_range",
        "str",
        "1h",
        "Default historical telemetry report range.",
        "Telemetry",
        120,
        "Selects the initial bounded Reports query.",
        apply="live",
        allowed=("15m", "1h", "6h", "24h", "7d", "30d"),
    ),
    _s(
        "default_theme_id",
        "str",
        "pa",
        "Instance fallback theme ID.",
        "Appearance",
        10,
        "Changes appearance for users without a preference.",
        apply="live",
        scope="user",
        validator="theme_id",
    ),
    _s(
        "release_track",
        "str",
        "release",
        "Install/update release track.",
        "Updates",
        10,
        "Changes which releases update checks and installs select.",
        apply="reload",
        aliases=("update_channel",),
        environment=("PA_RELEASE_TRACK", "PA_UPDATE_CHANNEL"),
        allowed=("release", "beta", "alpha", "dev", "pypi"),
        normalizer="release_track",
        migration="github/stable → release; main → dev",
    ),
    _s(
        "update_repo",
        "str",
        "petersky/pa",
        "GitHub repository used for update checks.",
        "Updates",
        20,
        "Changes the trusted source of executable updates.",
        apply="reload",
        validator="github_repository",
        example="petersky/pa",
    ),
    _s(
        "install_method",
        "str",
        "uv-tool",
        "Detected installation mechanism.",
        "Updates",
        30,
        "Used to select safe update behavior.",
        exposure="read_only",
        rationale="Detected and managed by installer/update workflows.",
        sources=("default", "environment"),
        allowed=("uv-tool", "source", "container"),
    ),
)

SETTINGS: dict[str, SettingDefinition] = {item.key: item for item in _DEFINITIONS}
ALIASES: dict[str, str] = {
    alias: item.key for item in _DEFINITIONS for alias in item.aliases
}

if len(SETTINGS) != len(_DEFINITIONS):  # pragma: no cover - import-time invariant
    raise RuntimeError("Duplicate canonical configuration key")


def _env_only(
    key: str,
    environment: str,
    description: str,
    category: str,
    order: int,
    *,
    secret: bool = False,
    deprecated: bool = False,
    replacement: str | None = None,
    migration: str | None = None,
    rationale: str,
) -> SettingDefinition:
    exposure: Exposure = (
        "hidden" if secret or category == "Internal runtime" else "read_only"
    )
    return _s(
        key,
        "optional_str",
        None,
        description,
        category,
        order,
        rationale,
        exposure=exposure,
        rationale=rationale,
        environment=(environment,),
        sources=("environment",),
        secret=secret,
        deprecated=deprecated,
        replacement=replacement,
        migration=migration,
    )


# Environment-only controls are part of the same registry but are not persisted
# InstanceConfig fields.  They are deliberately read-only/hidden in general
# configuration surfaces, with a rationale and the dedicated workflow that owns
# them.  Presence may be audited; values are never returned.
_ENVIRONMENT_ONLY_DEFINITIONS = (
    _env_only(
        "github_token",
        "PA_GITHUB_TOKEN",
        "PR-supervisor GitHub credential.",
        "Integration credentials",
        10,
        secret=True,
        rationale="Use the GitHub integration credential workflow; general configuration must not reveal or copy provider tokens.",
    ),
    _env_only(
        "github_webhook_secret",
        "PA_GITHUB_WEBHOOK_SECRET",
        "GitHub webhook verification secret.",
        "Integration credentials",
        20,
        secret=True,
        rationale="Use the GitHub integration credential workflow so rotation and webhook validation remain coordinated.",
    ),
    _env_only(
        "uv_bin",
        "PA_UV_BIN",
        "Absolute uv executable override.",
        "Bootstrap",
        10,
        rationale="Bootstrap-only path used before instance configuration is available; manage it in the service environment.",
    ),
    _env_only(
        "owner_api_url",
        "PA_OWNER_API_URL",
        "Private owner-channel HTTP endpoint.",
        "Internal runtime",
        10,
        secret=False,
        rationale="Bootstrap transport fencing is generated by PA and must not be changed through the served configuration API.",
    ),
    _env_only(
        "owner_socket",
        "PA_OWNER_SOCKET",
        "Private owner-channel Unix socket.",
        "Internal runtime",
        20,
        secret=False,
        rationale="Bootstrap transport fencing is generated by PA and must not be changed through the served configuration API.",
    ),
    _env_only(
        "runtime_dir",
        "PA_RUNTIME_DIR",
        "Private runtime socket directory.",
        "Bootstrap",
        20,
        rationale="Selected before the owner channel starts; configure it in the service manager.",
    ),
    _env_only(
        "local_api_url",
        "PA_LOCAL_API_URL",
        "Per-process authenticated owner API URL.",
        "Internal runtime",
        30,
        secret=False,
        rationale="Injected into PA-launched MCP processes and fenced to the owning instance.",
    ),
    _env_only(
        "local_api_socket",
        "PA_LOCAL_API_SOCKET",
        "Per-process owner API socket.",
        "Internal runtime",
        40,
        secret=False,
        rationale="Injected into PA-launched MCP processes and fenced to the owning instance.",
    ),
    _env_only(
        "local_api_token",
        "PA_LOCAL_API_TOKEN",
        "Per-process owner API bearer.",
        "Internal runtime",
        50,
        secret=True,
        rationale="Ephemeral child-process credential generated and rotated by PA.",
    ),
    _env_only(
        "local_api_endpoint_type",
        "PA_LOCAL_API_ENDPOINT_TYPE",
        "Owner endpoint diagnostic classification.",
        "Internal runtime",
        60,
        secret=False,
        rationale="Generated telemetry, not operator configuration.",
    ),
    _env_only(
        "cli_token",
        "PA_CLI_TOKEN",
        "User CLI bearer token.",
        "Internal runtime",
        70,
        secret=True,
        rationale="Managed by `pa login` and the user credential store.",
    ),
    _env_only(
        "pr_supervisor_token",
        "PA_PR_SUPERVISOR_TOKEN",
        "PR-supervisor replica credential.",
        "Internal runtime",
        80,
        secret=True,
        rationale="Issued and rotated by fenced PR-supervisor replication.",
    ),
    _env_only(
        "fleet_token",
        "PA_FLEET_TOKEN",
        "One-time fleet join token.",
        "Internal runtime",
        90,
        secret=True,
        rationale="Short-lived input to the authenticated fleet join workflow; never persist it as general configuration.",
    ),
    _env_only(
        "execution_context",
        "PA_EXECUTION_CONTEXT",
        "Signed agent execution provenance.",
        "Internal runtime",
        100,
        secret=True,
        rationale="Generated per dispatch and fenced to a leased card/session workspace.",
    ),
    _env_only(
        "assigned_service_mode",
        "PA_ASSIGNED_SERVICE_MODE",
        "Restricted assigned-service MCP mode marker.",
        "Internal runtime",
        101,
        rationale="Generated for one PA-managed Goal session and interpreted only by the restricted MCP bootstrap.",
    ),
    _env_only(
        "assigned_service_dispatch_id",
        "PA_ASSIGNED_SERVICE_DISPATCH_ID",
        "Restricted assigned-service dispatch binding.",
        "Internal runtime",
        102,
        rationale="Generated from the durable Goal dispatch and never accepted as operator configuration.",
    ),
    _env_only(
        "assigned_service_session_id",
        "PA_ASSIGNED_SERVICE_SESSION_ID",
        "Restricted assigned-service session binding.",
        "Internal runtime",
        103,
        rationale="Generated from the target-allocated durable session and never accepted as operator configuration.",
    ),
    _env_only(
        "assigned_service_credential",
        "PA_ASSIGNED_SERVICE_CREDENTIAL",
        "Legacy assigned-service bearer credential.",
        "Internal runtime",
        104,
        secret=True,
        rationale="Retained only so restricted bootstrap can reject legacy provider-visible Goal credentials.",
    ),
    _env_only(
        "assigned_service_authority_url",
        "PA_ASSIGNED_SERVICE_AUTHORITY_URL",
        "Legacy provider-visible Goal authority URL.",
        "Internal runtime",
        105,
        secret=True,
        rationale="Retained only so restricted bootstrap can reject caller-selected Goal authority routing.",
    ),
    _env_only(
        "assigned_service_authority_instance_id",
        "PA_ASSIGNED_SERVICE_AUTHORITY_INSTANCE_ID",
        "Legacy provider-visible Goal authority identity.",
        "Internal runtime",
        106,
        secret=True,
        rationale="Retained only so restricted bootstrap can reject caller-selected Goal authority identity.",
    ),
    _env_only(
        "writable_roots",
        "PA_WRITABLE_ROOTS",
        "Per-session filesystem write boundary.",
        "Internal runtime",
        110,
        secret=False,
        rationale="Generated from the durable workspace lease and sandbox policy.",
    ),
    _env_only(
        "dependency_cache",
        "PA_DEPENDENCY_CACHE",
        "Per-session dependency cache path.",
        "Internal runtime",
        120,
        secret=False,
        rationale="Generated from the leased execution workspace.",
    ),
    _env_only(
        "listener_health",
        "PA_LISTENER_HEALTH",
        "Bound listener health snapshot.",
        "Internal runtime",
        130,
        secret=False,
        rationale="Generated runtime telemetry, not operator configuration.",
    ),
    _env_only(
        "browser_cdp_url",
        "PA_BROWSER_CDP_URL",
        "Attached browser CDP endpoint.",
        "Internal runtime",
        140,
        secret=True,
        rationale="Generated per isolated browser attachment and scoped to one agent session.",
    ),
    _env_only(
        "browser_target_id",
        "PA_BROWSER_TARGET_ID",
        "Attached browser target ID.",
        "Internal runtime",
        150,
        secret=True,
        rationale="Generated per isolated browser attachment and scoped to one agent session.",
    ),
    _env_only(
        "browser_attachment_id",
        "PA_BROWSER_ATTACHMENT_ID",
        "Browser attachment ID.",
        "Internal runtime",
        160,
        secret=True,
        rationale="Generated by the browser manager.",
    ),
    _env_only(
        "browser_session_id",
        "PA_BROWSER_SESSION_ID",
        "Browser owner session ID.",
        "Internal runtime",
        170,
        secret=True,
        rationale="Generated by the browser manager.",
    ),
    _env_only(
        "browser_executable",
        "PA_BROWSER_EXECUTABLE",
        "Chromium executable override.",
        "Bootstrap",
        30,
        rationale="Host/platform discovery override; manage it in the service environment until a browser-provider setting is available.",
    ),
    _env_only(
        "browser_width",
        "PA_BROWSER_WIDTH",
        "Default isolated browser width.",
        "Bootstrap",
        40,
        rationale="Process-level browser default; per-session resize remains available through browser controls.",
    ),
    _env_only(
        "browser_height",
        "PA_BROWSER_HEIGHT",
        "Default isolated browser height.",
        "Bootstrap",
        50,
        rationale="Process-level browser default; per-session resize remains available through browser controls.",
    ),
    _env_only(
        "acp_quiesce",
        "PA_ACP_QUIESCE",
        "Shutdown ACP quiesce guard.",
        "Internal runtime",
        180,
        secret=False,
        rationale="One-shot lifecycle fence managed by PA restart/update orchestration.",
    ),
    _env_only(
        "acp_resume",
        "PA_ACP_RESUME",
        "Startup ACP resume guard.",
        "Internal runtime",
        190,
        secret=False,
        rationale="One-shot lifecycle fence managed by PA restart/update orchestration.",
    ),
    _env_only(
        "fleet_overview_refresh",
        "PA_FLEET_OVERVIEW_REFRESH",
        "Background fleet overview probe loop.",
        "Internal runtime",
        191,
        secret=False,
        rationale="Process-level override so TestClient boots do not start the long-lived Fleet refresh loop.",
    ),
    _env_only(
        "provider_result",
        "PA_PROVIDER_RESULT",
        "Provider action result marker.",
        "Internal runtime",
        200,
        secret=True,
        rationale="Child-process protocol value parsed only by the provider action runner.",
    ),
    _env_only(
        "config_color",
        "PA_CONFIG_COLOR",
        "Terminal configuration color policy.",
        "User interface",
        10,
        rationale="Per-shell presentation preference; use NO_COLOR or the process environment.",
    ),
    _env_only(
        "release_agent",
        "PA_RELEASE_AGENT",
        "Maintainer release-notes agent command.",
        "Maintainer tooling",
        10,
        rationale="Release-command-only override with a corresponding CLI flag.",
    ),
    _env_only(
        "release_agent_args",
        "PA_RELEASE_AGENT_ARGS",
        "Maintainer release-notes agent arguments.",
        "Maintainer tooling",
        20,
        rationale="Release-command-only override with a corresponding CLI flag.",
    ),
    _env_only(
        "release_agent_timeout",
        "PA_RELEASE_AGENT_TIMEOUT",
        "Maintainer release-notes timeout.",
        "Maintainer tooling",
        30,
        rationale="Release-command-only override with a corresponding CLI flag.",
    ),
    _env_only(
        "release_agent_use_stdin",
        "PA_RELEASE_AGENT_USE_STDIN",
        "Pass release prompt over stdin.",
        "Maintainer tooling",
        40,
        rationale="Release-command-only compatibility switch.",
    ),
    _env_only(
        "legacy_realm",
        "PA_REALM",
        "Legacy primary-realm selector.",
        "Compatibility",
        10,
        deprecated=True,
        replacement="subscribed_realms",
        migration="A single PA_REALM value migrates to subscribed_realms[0].",
        rationale="Accepted only by install/join compatibility paths; use subscribed_realms.",
    ),
    _env_only(
        "install_channel",
        "PA_CHANNEL",
        "Remote installer release track.",
        "Bootstrap",
        60,
        rationale="Installer-only alias used before config.json exists; use release_track after initialization.",
    ),
    _env_only(
        "git_ref",
        "PA_GIT_REF",
        "Remote installer Git revision override.",
        "Bootstrap",
        70,
        rationale="Installer-only source pin used before PA starts.",
    ),
    _env_only(
        "skip_service",
        "PA_SKIP_SERVICE",
        "Skip host service installation.",
        "Bootstrap",
        80,
        rationale="Installer-only control used before PA starts.",
    ),
    _env_only(
        "installer_github_repository",
        "PA_GITHUB_REPO",
        "Remote installer GitHub repository.",
        "Bootstrap",
        90,
        rationale="Installer-only source selector used before PA starts; use update_repo for runtime update checks.",
    ),
)
ENVIRONMENT_ONLY: dict[str, SettingDefinition] = {
    item.key: item for item in _ENVIRONMENT_ONLY_DEFINITIONS
}
REGISTRY: dict[str, SettingDefinition] = {**SETTINGS, **ENVIRONMENT_ONLY}


def get_setting(key: str) -> SettingDefinition:
    canonical = ALIASES.get(key, key)
    try:
        return SETTINGS[canonical]
    except KeyError as exc:
        known = ", ".join(sorted((*SETTINGS, *ALIASES)))
        raise KeyError(
            f"Unknown configuration key {key!r}. Known keys: {known}"
        ) from exc


def registry_metadata() -> dict[str, Any]:
    return {
        "schema_version": 1,
        "precedence": list(CONFIGURATION_PRECEDENCE),
        "settings": [
            item.metadata()
            for item in sorted(
                (*_DEFINITIONS, *_ENVIRONMENT_ONLY_DEFINITIONS),
                key=lambda value: (value.category, value.order),
            )
        ],
    }
